version: '3'
services:
  elasticsearch:
    container_name: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9201"
    networks:
      - elastic
  kibana:
    container_name: kib02
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - "5602:5602"
    environment:
      ELASTICSEARCH_URL: http://es02:9201
      ELASTICSEARCH_HOSTS: http://es02:9201
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
